SongsListTutorial/Models/Genre.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SongsListTutorial.Models {
    public class Genre {
        public string GenreID { get; set; }
        public string Name { get; set; }
    }
}

SongsListTutorial/Models/Song.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SongsListTutorial.Models {
    public class Song {
        public int SongId { get; set; }
        
        [Required(ErrorMessage = "Please enter a song name.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter a year.")]
        [Range(1900, 2021, ErrorMessage = "Year must be bewteen 1900 and 2021.")]
        public int? Year { get; set; }

        [Required(ErrorMessage = "Please enter a rating.")]
        [Range(1, 5, ErrorMessage = "The rating range must be between 1 and 5.")]
        public int? Rating { get; set; }

        [Required(ErrorMessage ="Please enter a genre.")]
        public string GenreID { get; set; } //foreign key to Genre model
        public Genre Genre { get; set; }

        public string Slug => Name?.Replace(' ', '-') + '-' + Year?.ToString();
    }
}

SongsListTutorial/Models/SongContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SongsListTutorial.Models {
    public class SongContext : DbContext {
        public DbSet<Song> Songs { get; set; }
        public DbSet<Genre> Genres { get; set; }

        public SongContext(DbContextOptions<SongContext> options) : base(options) {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            modelBuilder.Entity<Genre>().HasData(
                new Genre { GenreID = "M", Name = "Metal" },
                new Genre { GenreID = "R", Name = "Rap" },
                new Genre { GenreID = "H", Name = "Hi Hop" },
                new Genre { GenreID = "RC", Name = "Rock" }
            );

            modelBuilder.Entity<Song>().HasData(
                new Song {
                    SongId = 1,
                    Name = "Master of Puppets",
                    Year = 1980,
                    Rating = 5,
                    GenreID = "M"
                },
                new Song {
                    SongId = 2,
                    Name = "Wonderwall",
                    Year = 1990,
                    Rating = 4,
                    GenreID = "RC"

                },
                new Song {
                    SongId = 3,
                    Name = "Lose Yourself",
                    Year = 2005,
                    Rating = 1,
                    GenreID = "R"
                }
            );
        }
    }
}

SongsListTutorial/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SongsListTutorial.Models;

namespace SongsListTutorial.Controllers {
    public class HomeController : Controller {
        private SongContext context;

        public HomeController(SongContext context) {
            this.context = context;
        }

        public IActionResult Index() {
            var songs = context.Songs.Include(m => m.Genre).OrderBy(m => m.Name).ToList();
            return View(songs);
        }
    }
}

SongsListTutorial/Controllers/SongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SongsListTutorial.Models;

namespace SongsListTutorial.Controllers {
    public class SongController : Controller {
        private SongContext context;

        public SongController(SongContext context) {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Add() {
            ViewBag.Action = "Add";
            ViewBag.Genres = context.Genres.OrderBy(m => m.Name).ToList();
            return View("Edit", new Song());
        }

        [HttpGet]
        public IActionResult Edit(int songId) {
            ViewBag.Action = "Edit";
            ViewBag.Genres = context.Genres.OrderBy(m => m.Name).ToList();
            var song = context.Songs.Find(songId);
            return View(song);
        }

        [HttpPost]
        public IActionResult Edit(Song song) {
            if (ModelState.IsValid) {
                //Add song
                if (song.SongId == 0) {
                    context.Songs.Add(song);
                }
                else {
                    //Edit song
                    context.Songs.Update(song);
                }
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else {
                //If there is an issue with the model, redirect back to user
                ViewBag.Action = song.SongId == 0 ? "Add" : "Edit";
                ViewBag.Genres = context.Genres.OrderBy(m => m.Name).ToList();
                return View(song);
            }
        }

        [HttpGet]
        public IActionResult Delete(int songId) {
            var song = context.Songs.Find(songId);
            return View(song);
        }

        [HttpPost]
        public IActionResult Delete(Song song) {
            context.Songs.Remove(song);
            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

SongsListTutorial/Views/Home/Index.cshtml
@model List<Song>

@{
	ViewBag.Title = "My Songs";
}

<a asp-controller="Song" asp-action="Add">Add New Song</a>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>Name</th>
			<th>Year</th>
			<th>Genre</th>
			<th>Rating</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		@foreach (var song in Model) {
			<tr>
				<td>@song.Name</td>
				<td>@song.Year</td>
				<td>@song.Genre.Name</td>
				<td>@song.Rating</td>
				<td>
					<a asp-controller="Song" asp-action="Edit" asp-route-songId="@song.SongId" asp-route-slug="@song.Slug">Edit</a>
					<a asp-controller="Song" asp-action="Delete" asp-route-songId="@song.SongId" asp-route-slug="@song.Slug">Delete</a>
				</td>
			</tr>
		}

	</tbody>
</table>

SongsListTutorial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Songs List Tutorial</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SongsListTutorial
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SongsListTutorial/Views/Song/Delete.cshtml
@model Song

@{ 
    ViewBag.Title = "Delete Song";
}

<h2>Confirm Deletion</h2>
<h3>@Model.Name @Model.Year</h3>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="SongId" />
    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-controller="Home" asp-action="Index" class="btn btn-light">Cancel</a>
</form>

SongsListTutorial/Views/Song/Edit.cshtml
@model Song

@{
    ViewBag.Title = ViewBag.Action + " song";
}

<h2>@ViewBag.Title</h2>

<form asp-action="Edit" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    @* Name *@
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" />
    </div>

    @* Year *@
    <div class="form-group">
        <label asp-for="Year">Year</label>
        <input asp-for="Year" class="form-control" />
    </div>

    @* Genre *@
    <div class="form-group">
        <label asp-for="GenreID">Genre</label>

        <select asp-for="GenreID" class="form-control">
            <option value="">Select Genre</option>
            @foreach (Genre genre in ViewBag.Genres) {
                <option value="@genre.GenreID">@genre.Name</option>
            }
        </select>
    </div>

    @* Rating *@
    <div class="form-group">
        <label asp-for="Rating">Rating</label>
        <input asp-for="Rating" class="form-control" />

        <input type="hidden" asp-for="SongId" />
    </div>

    @* CRUD buttons *@
    <div class="form-group">
        <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-light">Cancel</a>
    </div>
</form>